name: flutter_phone_lib
description: Use VoIP in Flutter.
version: 0.0.41
repository: https://github.com/open-voip-alliance/flutter-phone-lib

environment:
  flutter: ">=3.24.0"
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  meta: ^1.16.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1

flutter:
  plugin:
    platforms:
      android:
        package: org.openvoipalliance.flutterphonelib
        pluginClass: PhoneLib
      ios:
        pluginClass: PhoneLibPlugin